version: 2.1  # CircleCI configuration version

jobs:
  build-test:
    docker:
      - image: cimg/python:3.10  # Specify the Python version using a Docker image
      - image: cimg/postgres:14.0  # Use an appropriate PostgreSQL version with required environment variables
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres

    steps:
      - checkout  # Checkout your code repository

      # Restore the cached Python packages to speed up dependency installation
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Install dependencies
          command: pip install -r requirements.txt  # Install project dependencies

      - save_cache:
          key: v1-dependencies-{{ checksum "requirements.txt" }}
          paths:
            - ~/.cache/pip  # Cache the Python packages for future builds

      - run:
          name: Run tests
          command: |
            python manage.py test

  test-coverage:
    docker:
      - image: cimg/python:3.10  # Specify the Python version for coverage reporting
      - image: cimg/postgres:14.0  # Use an appropriate PostgreSQL version with required environment variables
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
          
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Install dependencies
          command: pip install -r requirements.txt  # Install dependencies for coverage

      - run:
          name: Run coverage
          command: |
            coverage run manage.py test
            coverage xml

      - save_cache:
          key: v1-coverage-{{ checksum "requirements.txt" }}
          paths:
            - .coverage  # Cache coverage data for future reference

  push-to-dockerhub:
    docker:
      - image: cimg/python:3.10  # Specify the Python version for coverage reporting
      - image: cimg/postgres:14.0  # Use an appropriate PostgreSQL version with required environment variables
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
            
    steps:
      - checkout # Step to check out the source code
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME .
          # Build a Docker image using the specified IMAGE_NAME

      - run:
          name: Push to DockerHub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

            # Push the built image to Docker Hub with the 'latest' tag
            docker tag $IMAGE_NAME:latest $DOCKERHUB_USERNAME/$IMAGE_NAME
            docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest

workflows:
  version: 2  # Define a workflow for the CI/CD pipeline

  build-test:
    jobs:
      - build-test  # Run the 'build-test' job for building and testing
      - test-coverage:
          requires:
            - build-test  # Require the 'build-test' job to complete before running coverage
      - push-to-dockerhub:
          requires:
            - test-coverage  # Require the 'test-coverage' job to complete before running dockerhub