# CircleCI configuration version
version: 2.1

# Define custom commands that can be used in jobs
commands:

  # Install AWS CLI v2
  install_awscli:
    description: Install AWS CLI v2
    steps:
      - run:
          name: Install AWS CLI v2
          command: |
            # Download and install AWS CLI v2
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install

  # Destroy cloudformation stacks given a workflow ID
  destroy-environment:
    description: Destroy cloudformation stacks given a workflow ID.
    parameters:
      Workflow_ID:
        type: string
        default: ${CIRCLE_WORKFLOW_ID:0:7}
    steps:
      - run:
          name: Destroy environments
          when: on_fail  # Run only on job failure
          command: |
            # Delete a CloudFormation stack using the specified Workflow ID
            aws cloudformation delete-stack --stack-name $STACK_NAME-<< parameters.Workflow_ID >>

# Define individual jobs that can be executed in the workflow
jobs:

  # Build and test job
  build-test:
    # Primary container image where all commands run
    docker:
      - image: cimg/python:3.10
        environment:
          TEST_DATABASE_URL: postgresql://postgres@localhost/circle_test

    # Service container image
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: postgres

    steps:
      - checkout  # Checkout your code repository

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Install dependencies
          command: pip install -r requirements.txt  # Install project dependencies

      - save_cache:
          key: v1-dependencies-{{ checksum "requirements.txt" }}
          paths:
            - ~/.cache/pip  # Cache the Python packages for future builds

      - run:
          name: Run tests
          command: |
            python manage.py test

  # Test coverage job
  test-coverage:
    # Primary container image where all commands run
    docker:
      - image: cimg/python:3.10
        environment:
          TEST_DATABASE_URL: postgresql://postgres@localhost/circle_test

    # Service container image
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: postgres

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Install dependencies
          command: pip install -r requirements.txt  # Install dependencies for coverage

      - run:
          name: Run coverage
          command: |
            coverage run manage.py test
            coverage xml

      - save_cache:
          key: v1-coverage-{{ checksum "requirements.txt" }}
          paths:
            - .coverage  # Cache coverage data for future reference

  # Push to Docker Hub job
  push-to-dockerhub:
    # Primary container image where all commands run
    docker:
      - image: cimg/python:3.10
        environment:
          TEST_DATABASE_URL: postgresql://postgres@localhost/circle_test

    # Service container image
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: postgres

    steps:
      - checkout # Step to check out the source code
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME .
          # Build a Docker image using the specified IMAGE_NAME

      - run:
          name: Push to DockerHub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

            # Tag and push the built image to Docker Hub with the 'latest' tag
            docker tag $IMAGE_NAME:latest $DOCKERHUB_USERNAME/$IMAGE_NAME
            docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest

  # Deploy EC2 instance job
  deploy-ec2-instance:
    docker:
      - image: cimg/base:stable

    steps:
      - checkout  # Checkout your code
      - install_awscli

      - run:
          name: Deploy CloudFormation Stack
          command: |
            # Configure AWS CLI with your AWS credentials
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region $AWS_DEFAULT_REGION

            # Deploy the CloudFormation stack
            aws cloudformation deploy \
              --template-file .circleci/files/cloudformation_template.yml \
              --tags project=$STACK_NAME \
              --stack-name "$STACK_NAME-${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides \
                  SECRET_KEY: $SECRET_KEY \
                  DEBUG: $DEBUG \
                  ALLOWED_HOSTS: $ALLOWED_HOSTS \
                  AT_API_KEY: $AT_API_KEY \
                  AT_USERNAME: $AT_USERNAME \
                  DB_ENGINE: $DB_ENGINE \
                  DB_NAME: $DB_NAME \
                  DB_USER: $DB_USER \
                  DB_PASSWORD: $DB_PASSWORD \
                  DB_HOST: $DB_HOST \
                  DB_PORT: $DB_PORT \
                  DJANGO_SUPERUSER_USERNAME: $DJANGO_SUPERUSER_USERNAME \
                  DJANGO_SUPERUSER_EMAIL: $DJANGO_SUPERUSER_EMAIL \
                  DJANGO_SUPERUSER_PASSWORD: $DJANGO_SUPERUSER_PASSWORD \
                  DOCKERHUB_USERNAME: $DOCKERHUB_USERNAME \
                  DOCKERHUB_PASS: $DOCKERHUB_PASS
      
      - destroy-environment  # Run the destroy-environment command to delete resources

# Define the workflow for the CI/CD pipeline
workflows:
  version: 2

  build-test:
    jobs:
      - build-test  # Run the 'build-test' job for building and testing
      - test-coverage:
          requires:
            - build-test  # Require the 'build-test' job to complete before running coverage
      - push-to-dockerhub:
          requires:
            - test-coverage  # Require the 'test-coverage' job to complete before pushing to Docker Hub
      - deploy-ec2-instance:
          requires:
            - push-to-dockerhub  # Require the 'push-to-dockerhub' job to complete before deploying the EC2 instance
